### PR TITLE
Moved source files to src/ and passed through elm-format tool

### PR DESCRIPTION
**Pull request by specious**
I think the code is now better organized and more approachable.

### CODE REVIEW

**Comment by kghandhi** [comment]
This reorganization looks good to me, let me know if you're ready for me to merge it in and I will!

**Comment by specious** [comment]
Yes, please do.

I have discovered that switching to relative paths to the static assets while also moving Main.elm to a subdirectory has resulted in elm-reactor not loading them.

@lukewestby responded to me on the [Elm Slack channel](http://elmlang.herokuapp.com/) and recommended that I use a leading `/` when working with elm-reactor.  That, however, means that the builds would need to be hosted at server root in order for the sounds and images to load.

use-slash-with-elm-reactor

Perhaps this is one of the various [current limitations](https://github.com/elm-lang/elm-reactor/issues) of elm-reactor that could be addressed inside that project over time.

**Comment by specious** [comment]
7fe2be26a7a5c8e45a86707b70540cf37fe08074 makes merging tricky, because:

```
$ git merge master
CONFLICT (modify/delete): Display.elm deleted in HEAD and modified in master. Version master of Display.elm left in tree.
```

**Comment by specious** [comment]
> This reorganization looks good to me, let me know if you're ready for me to merge it in and I will!

@kghandhi, does the offer still stand?

**Comment by specious** [comment]
Superseded by 1898d85632ef110d8c2903b3e525e1b259ab1c32,

**Pull request closed without merging**
