### PR TITLE
Upgraded to Elm 0.16

### PR DESCRIPTION
**Pull request by specious**
Followed the [official migration guide](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.16.md) and resolved all the compiler errors.

### CODE REVIEW

**Comment by metric-space** [comment]
@specious  I keep getting the following error message `Unable to find a set of packages that will work with your constraints` after clicking `display.elm`, any insight?

**Comment by specious** [comment]
@nerorevenge, are you running my fork as of commit f763bb5 using Elm 0.16?

**Comment by metric-space** [comment]
@specious my bad mate, I was under the impression 0.16 is the latest version, nevermind me. I guess work will have to be done for version 0.17. Probably something I can take a look at soon to speed my learning.

**Comment by specious** [comment]
@kghandhi, could you please review this pull request?

**Comment by kghandhi** [comment]
@specious Did you manage to fix it after the upgrade to 0.15? When we ( @asecular and I) upgraded to 0.15 the game overall stopped working because Evan changed the implementation of `lastPressed` (I think) to a different javascript function. 

Also thank you so much for your PR, Ill look into it today! I really appreciate the amount of work you put into making this upgrade!

**Comment by specious** [comment]
When I tried to run 3b84573 (the commit that I branched from) with Elm 0.15.1 I ran into:

```
Unable to find a set of packages that will work with your constraints.
```

However after three days of implementing all the changes needed to satisfy the Elm 0.16 compiler, the game fired up and worked right away.  Here I have it running with `elm-reactor 0.16.0`:

elm-pacman

Perhaps you can verify that the game works without any regressions.

**Comment by kghandhi** [comment]
@specious Im trying to run it, but I can't install elm 0.16 because the latest version is 0.17, are you saying it will not run for elm 0.17? Im also getting the "Unable to find a set of packages that will work with your constraints." error

**Comment by specious** [comment]
You can downgrade with `npm i -g elm@0.16.0` or you can use [elmenv](https://github.com/sonnym/elmenv).

**Comment by kghandhi** [comment]
Awesome, I got it running but the arrow key controls do not work at all. Do yours work?

**Comment by specious** [comment]
They do for me, though there appears to be roughly a one second lag.

**Comment by kghandhi** [comment]
Correction, it works in firefox! it is actually a little glitchy and we may need to mess with the speeds/times that may have changed a bit depending on the version or something, but this looks good to me! 👍

**Comment by specious** [comment]
Yeah, I just confirmed - the keys aren't working in Chrome, but do in Firefox.

**Comment by kghandhi** [comment]
and i think thats good enough for me, @asecular what do you think?

**Comment by specious** [comment]
It appears that `Keyboard.presses` is known to behave inconsistently across browsers: https://github.com/elm-lang/core/pull/463.

**Comment by kghandhi** [comment]
Its really too bad that it doesn't work in chrome because the speed/everything looks best in chrome.

**Comment by kghandhi** [comment]
Abe gave me the thumbs up, so Im going to go ahead and merge this!

**Pull request merged**
